export const environment = {
  production: true,
  socket: '/api/socket',
  apiUrl: '/api/auth',
  register: '/api/auth/register',
  login: '/api/auth/login',
  logout: '/api/home/logout',
  checkUsername: '/api/auth/checkUsername',
  loadContacts: '/api/home/loadContacts',
  searchUsers: '/api/home/searchUsers',
  addContact: '/api/home/addContact',
  loadMyMessages: '/api/message/loadMessages',
  storeSocketID: '/api/socket/storeSocketID',
  removeSocketID: '/api/socket/removeSocketID',
  checkOnline: '/api/message/checkOnline',
  updateMessageHeight: '/api/message/updateMsgHeight',
  updateMessageState: '/api/message/updateMsgState',
  updateScrollHeight: '/api/message/updateScrollHeight',
  checkIsOnCall: '/api/message/checkIsOnCall',
  editProfile: '/api/home/editProfile',
  changeProfilePic: '/api/home/changeProfilePicture',
  removeProfilePic: '/api/home/removeProfilePicture'
};
